### ISSUE TITLE
MAX_MEMBER_COUNT = 36

### ISSUE THREAD

**Issue by yarekc** [mganeko/browser_mcu_core#1]
Why 36 ? 
Is that an aribtrary limit you put ?

Would be great if you can publish a ready to test/benchmark product like a MCU or SFU server.
Looks very promising for now

**Comment by mganeko** [comment]
Thanks for paying attention to this repository.

36 is just my experience on my PC.
There is no strict reason.
But I think video will be too small, more than 36.

Test/benckmark are definitely  important.
But it is difficult to prepare / execute.
I would appreciate any ideas for examples of test code.

**Comment by yarekc** [comment]
Thanks for replaying me,

Sorry to communicate through github issues, but I don't have your email, nor skype. 
I think I have the global idea of what you are doing: you use chrome headless as webrtc server: correct ?
It looks like you use it as a MCU. Is there a way to use it as SFU (just to relay streams indeed).
That would be the simplest, lightest and FASTEST webrtc server ever made.

I really believe that SFU is the correct way for wbertc, so people can choose streams they want to watch and not just receive a whole bunch of mxied streams that they cannot control.
Do you think you would be able to create an SFU server from headless chrome ?

Regards
(if you can join your email or skype, that would help me not to pollute your github account)
Mine is: yarekc@gmail.com, skype: proxymis

**Comment by mganeko** [comment]
Yes, I am trying to build MCU with headless chrome.
It is already working in https://github.com/mganeko/browser_mcu_server.

I agree with you that SFU is very efficient system.
SFU does not decode / encode media streams.
On the other hand, browser always decodes media stream at receiver, and always encodes media at sender.
So I am afraid that it is not possible to build SFU with browser.

**Comment by yarekc** [comment]
what about relaying a peer like: 
https://webrtc.github.io/samples/src/content/peerconnection/multiple-relay/

my idea is simply to use chrome betweeen 2 users
user1<------>chrome headless (relay the peer) <------>user2

of course chrome headless runs on a powerful server that can handle lot of bandwidth and CPU so it can support N peers.

**Comment by mganeko** [comment]
Thanks for example of relay.
This relay does decode / encode. So every action of "Insert relay" increase delay and video quality get worse.

It is possible to relay media stream using browser with decode / encode, but it is "pseudo" SFU.
In case of 4 members, "pseudo" SFU needs 4 decode and 12 encode.
I think it is too heavy.

MCU needs 4 decode, 1 mix, 4 encode.

"Real" SFU needs no decode, no encode. But unfortunately it is not possible with browser.

**Comment by mganeko** [comment]
keep the limit. close
